name: Test Suite

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, reopened, synchronize ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        ports:
          - 9200:9200
    steps:
      - uses: actions/checkout@v3
      - name: Wait for Container Services
        run: sleep 60
      - name: Check Elasticsearch Logs
        run: docker logs $(docker ps -q --filter ancestor=docker.elastic.co/elasticsearch/elasticsearch:8.12.2)

